steps:
- name: 'eu.gcr.io/test-project-278516/php7.1.33_drupal'
  args: ['composer', 'install']
- name: 'eu.gcr.io/test-project-278516/php7.1.33_drupal'
  args: ['zip -r drupal-artifact.zip *']
artifacts:
  objects:
    location: 'gs://drupal-artifact'
    paths: ['drupal-artifact.zip']